// Generated by scripts/build_large_airports.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::large_airports {

enum AirportCategory : uint8_t {
  kCatLarge = 0,
  kCatMedium = 1,
  kCatMilitary = 2,
  kCatSmall = 3,
};

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
  uint8_t category;
};

struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
};

constexpr size_t kAirportCount = 10525;
constexpr size_t kRunwayCount = 13942;

extern const Airport kAirports[];
extern const Runway kRunways[];

}  // namespace data::large_airports
